name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  PACKAGE_NAME: abremir.VLPause

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Package Assets
        run: |
          cd ./source && zip -r ../${{ env.PACKAGE_NAME }}.zip . && cd ..

      - name: Publish Github Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ env.PACKAGE_NAME }}.zip
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
